In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)

# the histogram of the data
n, bins, patches = plt.hist(x, 50, normed=1, facecolor='g', alpha=0.75)


plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$')
plt.axis([40, 160, 0, 0.03])
plt.grid(True)
plt.show()

In [23]:
import scipy.stats as sc
#plt.plot(patches)
#plt.show()
print patches[0]

Rectangle(40.8092,0;2.40329x8.32193e-05)

In [60]:
ht = {-1:'H',1:'T'}
htnames = np.vectorize(ht.get)
ctr = np.sign(np.random.randn(8))
coin_tosses = htnames(ctr)
list(coin_tosses).count('H')

4

In [54]:
sc.binom.pmf(4,8,0.5)

0.27343750000000017

In [69]:
import statsmodels
import pandas as pd

In [71]:
sydtrains = pd.read_csv('sydtrains.csv')
sydtrains

,LINE,STATION,YEAR,SURVEY_DATE_USED,WHETHER_SURVEYED,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,IN_24_HOURS,OUT_24_HOURS,RANK,STATION_SORT_ID
0,CBD,Central,2014,6/05/2014,Yes,940,920,10390,42070,21400,30150,45370,16270,19010,7700,"97,110","97,110",1,101
1,CBD,Town Hall,2014,7/05/2014,Yes,880,880,6380,43210,16930,23550,43670,15270,21760,6720,"89,620","89,620",2,102
2,CBD,Wynyard,2014,20/05/2014,Yes,590,570,4710,39620,9200,11180,35010,6510,10690,2330,"60,200","60,200",3,103
3,Western,Parramatta,2014,19/11/2014,Yes,660,330,7790,13700,7400,7020,14960,8660,4150,5260,"34,960","34,960",4,905
4,North Shore,North Sydney,2014,19/08/2014,Yes,270,270,2340,18340,4450,5590,17760,3050,3790,1360,"28,610","28,610",5,1402
5,CBD,Redfern,2014,1/05/2014,Yes,250,250,3910,10690,5350,8170,12510,4250,3660,2320,"25,680","25,680",6,108
6,North Shore,Chatswood,2014,19/08/2014,Yes,210,200,5030,8200,4710,4930,9430,6000,2820,2860,"22,200","22,200",7,1407
7,Eastern Suburbs,Bondi Junction,2014,2/09/2014,Yes,210,210,10150,4350,4370,4600,5240,8330,1910,4380,"21,880","21,880",8,203
8,Inner West,Strathfield,2014,9/09/2014,Yes,190,190,7900,4050,4980,3950,5540,7230,2100,5280,"20,710","20,710",9,1110
9,CBD,Circular Quay,2014,22/05/2014,Yes,200,200,2110,8750,4340,6710,9910,3380,4070,1600,"20,630","20,630",10,104
10,CBD,Martin Place,2014,27/05/2014,Yes,200,190,590,14250,2900,3420,12340,1790,4600,970,"20,630","20,630",10,107
11,Illawarra,Hurstville,2014,28/05/2014,Yes,160,160,7790,2200,5230,4180,3840,7450,1270,4290,"18,290","18,290",12,310
12,North Shore,St Leonards,2014,27/05/2014,Yes,170,170,3420,8900,3090,3310,8780,3230,2130,1990,"17,590","17,590",13,1405
13,Western,Blacktown,2014,14/10/2014,Yes,190,210,6460,3370,4270,3450,4600,7090,1040,2450,"16,560","16,560",14,911
14,Inner West,Burwood,2014,9/09/2014,Yes,140,140,4850,2930,4470,3670,4020,5060,1510,3190,"14,990","14,990",15,1109
15,Eastern Suburbs,Kings Cross,2014,3/09/2013,No,120,120,3690,3820,3110,2670,4400,3640,1550,2620,"12,870","12,870",16,201
16,North Shore,Hornsby,2014,14/05/2014,Yes,210,100,5550,2260,3060,2390,2750,5200,680,2290,"12,250","12,250",17,1417
17,Inner West,Ashfield,2014,4/09/2013,No,100,100,5090,2010,2690,2220,2500,4500,820,2370,"11,200","11,200",18,1107
18,Illawarra,Kogarah,2014,19/06/2014,Yes,90,100,4000,2970,3150,2320,3210,3450,650,2260,"11,100","11,100",19,307
19,South,Lidcombe,2014,5/06/2014,Yes,100,100,4570,1620,2870,2210,2550,3900,820,3080,"10,910","10,910",20,702
20,Western,Auburn,2014,19/11/2014,Yes,130,60,3880,1790,3220,2900,2700,3890,960,2260,"10,890","10,890",21,901
21,CBD,Museum,2014,22/05/2014,Yes,100,100,800,6290,2220,2340,5980,1230,1760,910,"10,860","10,860",22,106
22,Northern via Strathfield,Epping,2014,21/05/2014,Yes,170,90,5700,1580,2130,1600,1970,4920,600,2380,"10,570","10,570",23,1208
23,Northern via Macquarie Park,Macquarie University,2014,21/05/2014,Yes,100,100,1310,3220,2570,3940,4530,1970,1580,860,"10,090","10,090",24,1303
24,CBD,St James,2014,27/05/2014,Yes,100,90,780,5880,1900,2160,5630,1120,1440,580,"9,850","9,850",25,105
25,Illawarra,Rockdale,2014,28/05/2014,Yes,90,90,4660,780,2610,2170,1670,3770,610,2820,"9,640","9,640",26,306
26,South,Cabramatta,2014,11/06/2014,Yes,150,80,3780,1070,2760,2820,1750,3760,290,1000,"8,730","8,730",27,708
27,Bankstown,Bankstown,2014,13/05/2014,Yes,80,60,3010,1810,2400,2570,2840,3130,300,1050,"8,630","8,630",28,612
28,South,Liverpool,2014,4/06/2014,Yes,150,80,2510,2270,2510,2260,2610,2650,570,1100,"8,350","8,350",29,710
29,Illawarra,Sutherland,2014,12/06/2014,Yes,140,70,4260,1460,1920,1650,1750,3900,250,1240,"8,320","8,320",30,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,Newcastle,Newcastle,2004,19/06/2003,No,50,20,260,320,720,850,430,200,70,140,1530,1530,123,1917
3338,Hunter,Waratah,2004,16/10/2001,No,0,0,100,100,150,150,120,120,40,30,410,410,193,2001
3339,Hunter,Warabrook (University),2004,16/10/2001,No,10,10,20,250,120,200,300,70,90,20,540,540,185,2002
3340,Hunter,Sandgate,2004,16/10/2001,No,0,0,10,10,10,10,20,20,0,0,40,40,267,2003
3341,Hunter,Hexham,2004,16/10/2001,No,0,0,10,20,10,20,20,10,10,0,50,50,258,2004
3342,Hunter,Tarro,2004,16/10/2001,No,0,0,20,0,0,10,0,10,0,0,20,20,278,2005
3343,Hunter,Beresfield,2004,16/10/2001,No,0,0,180,80,140,110,70,180,10,40,400,400,195,2006
3344,Hunter,Thornton,2004,16/10/2001,No,0,0,150,20,60,80,50,150,10,20,270,270,211,2007
3345,Hunter,Metford,2004,16/10/2001,No,0,0,100,20,50,50,20,90,10,10,180,180,231,2008
3346,Hunter,Victoria Street,2004,16/10/2001,No,0,0,190,50,120,120,70,180,20,50,400,400,195,2009
3347,Hunter,East Maitland,2004,16/10/2001,No,0,0,20,50,50,40,50,20,0,10,120,120,240,2010
3348,Hunter,High Street,2004,16/10/2001,No,0,0,30,40,40,40,30,40,10,0,110,110,248,2011
3349,Hunter,Maitland,2004,16/10/2001,No,0,10,190,100,180,210,150,180,20,40,540,540,185,2012
3350,Hunter,Telarah,2004,24/08/2004,Yes,0,0,110,30,60,60,50,120,20,30,240,240,218,2013
3351,Hunter,Mindaribba,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2014
3352,Hunter,Paterson,2004,24/08/2004,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,2015
3353,Hunter,Martins Creek,2004,24/08/2004,Yes,0,0,10,0,0,0,0,0,0,0,10,10,283,2016
3354,Hunter,Hilldale,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2017
3355,Hunter,Wallarobba,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2018
3356,Hunter,Wirragulla,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2019
3357,Hunter,Dungog,2004,24/08/2004,Yes,0,0,20,0,10,20,10,20,0,10,40,40,267,2020
3358,Hunter,Lochinvar,2004,24/08/2004,Yes,0,0,10,0,0,0,0,0,0,0,10,10,283,2021
3359,Hunter,Allandale,2004,16/10/2001,No,0,0,0,0,0,0,0,0,0,0,0,0,295,2022
3360,Hunter,Greta,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2023
3361,Hunter,Branxton,2004,24/08/2004,Yes,0,0,20,0,0,0,0,10,0,10,20,20,278,2024
3362,Hunter,Belford,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,0,0,0,295,2025
3363,Hunter,Singleton,2004,24/08/2004,Yes,0,0,30,10,0,0,10,30,10,10,50,50,258,2026
3364,Hunter,Muswellbrook,2004,24/08/2004,Yes,0,0,10,0,30,10,0,40,10,20,50,50,258,2027
3365,Hunter,Aberdeen,2004,24/08/2004,Yes,0,0,0,0,0,0,0,0,0,10,10,10,283,2028
3366,Hunter,Scone,2004,24/08/2004,Yes,10,0,0,0,0,0,0,10,0,0,10,10,283,2029